spring:
  jpa:
    open-in-view: false
    show-sql: false
  liquibase:
    enabled: false
#  datasource:
#    druid:
#      max-active: 20
#      initial-size: 10
#      max-wait: 60000
#      min-idle: 10
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      test-on-borrow: true
#      test-while-idle: true
#      validation-query: SELECT 1
#      url: jdbc:mysql://${database.host}/malls?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
       
access.control.allow.origin: '*'
    
